Repository dhis2/dhis2-android-skeleton-app, pull requests merged in 2019-06, with the labels that each got.

#10 fix: Junit config
  app/build.gradle
Labels: bug

#13 feat: Add D2 error activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/android/androidskeletonapp/ui/d2_errors/D2ErrorActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/d2_errors/D2ErrorAdapter.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/main/MainActivity.java
  app/src/main/res/drawable/circle_shape.xml
  app/src/main/res/drawable/ic_error_outline_black_24dp.xml
  app/src/main/res/layout/activity_d2_errors.xml
  app/src/main/res/layout/content_d2_errors.xml
  app/src/main/res/layout/d2_error_item.xml
  app/src/main/res/menu/activity_navigation_drawer.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#15 feat: Form activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/android/androidskeletonapp/data/service/forms/EnrollmentFormService.java
  app/src/main/java/com/example/android/androidskeletonapp/data/service/forms/RuleEngineService.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/enrollment_form/EnrollmentFormActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/enrollment_form/FieldHolder.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/enrollment_form/FormAdapter.java
  app/src/main/res/drawable/ic_send_black_24dp.xml
  app/src/main/res/layout/activity_enrollment_form.xml
  app/src/main/res/layout/item_field.xml
Labels: enhancement

#16 feat: Get user from usb
  app/src/main/java/com/example/android/androidskeletonapp/ui/main/MainActivity.java
Labels: enhancement

#17 feat: Add ListActivity, use in ErrorsActivity
  app/src/main/java/com/example/android/androidskeletonapp/ui/base/ListActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/d2_errors/D2ErrorActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/programs/ProgramsActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/tracked_entity_instances/TrackedEntityInstancesActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/tracked_entity_instances/search/TrackedEntityInstanceSearchActivity.java
Labels: refactor

#18 feat: Enrollment activity
  app/src/main/java/com/example/android/androidskeletonapp/data/service/ActivityStarter.java
  app/src/main/java/com/example/android/androidskeletonapp/data/service/forms/EnrollmentFormService.java
  app/src/main/java/com/example/android/androidskeletonapp/data/service/forms/RuleEngineService.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/programs/OnProgramSelectionListener.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/programs/ProgramsActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/programs/ProgramsAdapter.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/tracked_entity_instances/TrackedEntityInstancesActivity.java
  app/src/main/res/drawable/ic_add_white.xml
  app/src/main/res/layout/content_tracked_entity_instances.xml
Labels: enhancement

#21 fix: build config field for sdk version
  app/build.gradle
Labels: bug

#24 fix: Move layout ids to camel case
  app/src/main/java/com/example/android/androidskeletonapp/ui/d2_errors/D2ErrorActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/d2_errors/D2ErrorAdapter.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/login/LoginActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/main/MainActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/programs/ProgramsActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/programs/ProgramsAdapter.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/tracked_entity_instances/TrackedEntityInstanceAdapter.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/tracked_entity_instances/TrackedEntityInstancesActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/tracked_entity_instances/search/TrackedEntityInstanceSearchActivity.java
  app/src/main/res/layout/activity_d2_errors.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_navigation.xml
  app/src/main/res/layout/activity_programs.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/activity_tracked_entity_instance_search.xml
  app/src/main/res/layout/activity_tracked_entity_instances.xml
  app/src/main/res/layout/content_d2_errors.xml
  app/src/main/res/layout/content_main.xml
  app/src/main/res/layout/content_programs.xml
  app/src/main/res/layout/content_tracked_entity_instance_search.xml
  app/src/main/res/layout/content_tracked_entity_instances.xml
  app/src/main/res/layout/d2_error_item.xml
  app/src/main/res/layout/nav_header_navigation.xml
  app/src/main/res/layout/program_item.xml
  app/src/main/res/layout/tracked_entity_instance_item.xml
  app/src/main/res/menu/activity_navigation_drawer.xml
Labels: refactor

#30 fix: Fix metadata sync
  app/src/main/java/com/example/android/androidskeletonapp/ui/main/MainActivity.java
Labels: bug

#32 feat: Data states 2
  app/src/main/java/com/example/android/androidskeletonapp/ui/tracked_entity_instances/TrackedEntityInstanceAdapter.java
  app/src/main/res/drawable/ic_not_sync.xml
  app/src/main/res/drawable/ic_sync_problem.xml
  app/src/main/res/layout/list_item.xml
  app/src/main/res/layout/tracked_entity_instance_item.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#36 feat: Import conflicts
  app/src/main/java/com/example/android/androidskeletonapp/ui/base/ListActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/base/ListItemWithSyncHolder.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/base/SubListItemHolder.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/tracked_entity_instances/TrackedEntityInstanceAdapter.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/tracker_import_conflicts/TrackerImportConflictsAdapter.java
  app/src/main/res/layout/list_item.xml
  app/src/main/res/layout/sub_list_item.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#39 feat: Wipe data
  app/src/main/java/com/example/android/androidskeletonapp/ui/main/MainActivity.java
  app/src/main/res/layout/content_main.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#41 fix: Add android2 credentials
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: bug

#42 fix: Refactors and fixes
  app/src/main/java/com/example/android/androidskeletonapp/data/service/SyncStatusHelper.java
  app/src/main/java/com/example/android/androidskeletonapp/data/service/forms/EnrollmentFormService.java
  app/src/main/java/com/example/android/androidskeletonapp/data/service/forms/EventFormService.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/enrollment_form/EnrollmentFormActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/event_form/EventFormActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/main/MainActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/programs/ProgramsAdapter.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/tracked_entity_instances/TrackedEntityInstanceAdapter.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/tracked_entity_instances/TrackedEntityInstancesActivity.java
  app/src/main/java/com/example/android/androidskeletonapp/ui/tracked_entity_instances/search/TrackedEntityInstanceSearchActivity.java
  app/src/main/res/layout/content_main.xml
  app/src/main/res/layout/content_tracked_entity_instance_search.xml
Labels: bug
